config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: %i[new create show destroy] do
    resources :bookmarks, only: %i[new create destroy]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end
  
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path(@list.photo.key) if @list.photo.attached? %>)">
  <div class="container">
    <h1 class='text-center'>New</h1>
  </div>
</div>
<div class="new-bookmarks text-center mt-5 mx-5">
  <div class="new-bookmark">
    <%= simple_form_for [ @list, @bookmark ] do |f| %>
        <%= f.input :comment %>
        <%= f.association :movie %>
        <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2250&q=80);">
  <div class="container">
    <h1> The WatchList.com</h1>
    <p>Your watchlist, everywhere.</p>
    <%= link_to 'Create a new list', new_list_path, class: "btn btn-success" %>
  </div>
</div>

<div class="container">
  <div class="cards">
    <% @lists.each do |list|%>
      <%= link_to list_path(list) do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
          <%= list.name %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2250&q=80);">
  <div class="container">
    <h1 class='text-center'>New</h1>
  </div>
</div>

<div class="new-lists text-center mx-5">
  <div class="new-list">
    <h1>Create a new <strong>list</strong> !</h1>
    <%= simple_form_for(@list) do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Submit", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/lists/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://mpng.subpng.com/20180330/fow/kisspng-roll-film-logo-cinema-roll-5abe46881c4265.5821418815224193361158.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active nav-link">
        <%= link_to "My Movies", movies_path %>
      </li>
      <li class="nav-item nav-link">
        <%= link_to 'My lists', lists_path %>
      </li>
      <li class="nav-item nav-link">
        <%= link_to 'New list', new_list_path(@list) %>
      </li>

    </ul>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path(@list.photo.key) if @list.photo.attached? %>');">
  <div class="container">
    <h1 class='text-center'><%= @list.name %></h1>
  </div>
</div>

<div class="movie-cards">
  <div class="list-text">
    <h3>My Bookmarks</h3>
    <%= link_to 'Add a movie', new_list_bookmark_path(@list), class: "btn btn-success"  %>
  </div>
  <div class="movie-card">
      <% @bookmarks.each do |bookmark| %>
        <div class="list-group-item">
          <%= image_tag bookmark.movie.poster_url, class:"poster-img" %>
          <div class="movie-card-text">
            <h4><strong><%= bookmark.movie.title %> • <%= bookmark.movie.rating %><i class="fas fa-star star-yellow"></i></strong></h4>
            <p><%= bookmark.movie.overview %></p>
            <h4><em>"<%= bookmark.comment %>"</em></h4>
            <div class="show-delete">
              <%= link_to "Delete",
                  bookmark_path(bookmark),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
  </div>
<%= button_to "Delete list",
  list_path(@list),
  method: :delete,
  data: { confirm: "Are you sure?" }, class: "btn btn-success" %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://mpng.subpng.com/20180330/fow/kisspng-roll-film-logo-cinema-roll-5abe46881c4265.5821418815224193361158.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active nav-link">
      </li>
      <li class="nav-item nav-link">
        <%= link_to 'My lists', root_path, class:"a-nav" %>
      </li>
      <li class="nav-item nav-link">
        <%= link_to 'New list', new_list_path(@list), class:"a-nav" %>
      </li>

    </ul>
  </div>
</div>